# Generated by Django 5.0.3 on 2024-04-21 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espasa_info', '0001_initial'),
        ('multiple_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('id_att', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('error', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MeliCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('app_id', models.CharField(max_length=30)),
                ('client_secret', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('code_tg', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('refresh_secret', models.CharField(max_length=100)),
                ('user_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoAtributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pub_to_copy', models.CharField(help_text='Publicacion a copiar atributos, ej MLA12345', max_length=50, verbose_name='Copy ID')),
                ('atributos', models.ManyToManyField(blank=True, to='meli_api.atributo')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('video', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('imagenes', models.ManyToManyField(blank=True, to='multiple_upload.image')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('categoria', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('gold_premium', 'Gold Premium')], max_length=30)),
                ('desc_meli', models.TextField()),
                ('precio', models.IntegerField(default=0)),
                ('espasa_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='espasa_info.crm')),
                ('g_atributos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meli_api.grupoatributos')),
                ('g_imagenes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meli_api.grupoimagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('precio', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=30)),
                ('f_creado', models.DateTimeField(auto_now_add=True)),
                ('f_actualizacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('activa', models.BooleanField(blank=True, null=True)),
                ('visualizaciones', models.IntegerField(default=0, verbose_name='vistas')),
                ('clics_tel', models.IntegerField(default=0, verbose_name='boton tel')),
                ('url', models.URLField(default='sinurl.com.ar')),
                ('sincronizado', models.BooleanField(default=False)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meli_api.modelo')),
            ],
        ),
    ]
