# Generated by Django 5.0.3 on 2024-04-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold')], max_length=30)),
                ('f_creado', models.DateTimeField(auto_now_add=True)),
                ('f_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('attributos', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('imagenes', models.ManyToManyField(to='meli_api.imagen')),
            ],
        ),
    ]
