# Generated by Django 5.0.3 on 2024-04-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meli_api.modelo'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='visualizaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
