# Generated by Django 5.0.3 on 2024-04-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0002_publicacion_modelo_publicacion_visualizaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('id_att', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='url',
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
