# Generated by Django 5.0.3 on 2024-04-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0003_atributo_remove_imagen_url_imagen_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='attributos',
        ),
        migrations.AddField(
            model_name='modelo',
            name='atributos',
            field=models.ManyToManyField(to='meli_api.atributo'),
        ),
    ]
