# Generated by Django 5.0.3 on 2024-04-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0004_remove_modelo_attributos_modelo_atributos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeliCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=30)),
                ('client_secret', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('code_tg', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('refresh_secret', models.CharField(max_length=100)),
            ],
        ),
    ]
