# Generated by Django 5.0.3 on 2024-04-03 01:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0005_melicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='melicon',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
