# Generated by Django 5.0.3 on 2024-04-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0007_modelo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='atributos',
        ),
        migrations.CreateModel(
            name='GrupoAtributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('atributos', models.ManyToManyField(to='meli_api.atributo')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagenes', models.ManyToManyField(to='meli_api.imagen')),
            ],
        ),
        migrations.AddField(
            model_name='modelo',
            name='atributos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meli_api.grupoatributos'),
        ),
    ]
