# Generated by Django 5.0.3 on 2024-04-04 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0009_modelo_desc_meli_remove_modelo_imagenes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='atributos',
            new_name='g_atributos',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='imagenes',
            new_name='g_imagenes',
        ),
        migrations.AddField(
            model_name='grupoatributos',
            name='pub_to_copy',
            field=models.CharField(default=django.utils.timezone.now, help_text='Publicacion a copiar atributos, ej MLA12345', max_length=50, verbose_name='Copy ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(max_length=30),
        ),
    ]
