# Generated by Django 5.0.3 on 2024-04-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0010_rename_atributos_modelo_g_atributos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoatributos',
            name='atributos',
            field=models.ManyToManyField(blank=True, null=True, to='meli_api.atributo'),
        ),
    ]
