# Generated by Django 5.0.3 on 2024-04-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0012_alter_grupoatributos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='url',
            field=models.URLField(default='sinurl.com.ar'),
        ),
    ]
