# Generated by Django 5.0.3 on 2024-04-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0013_publicacion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='clics_tel',
            field=models.IntegerField(default=0, verbose_name='boton tel'),
        ),
        migrations.AlterField(
            model_name='grupoatributos',
            name='atributos',
            field=models.ManyToManyField(blank=True, to='meli_api.atributo'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='visualizaciones',
            field=models.IntegerField(default=0, verbose_name='vistas'),
        ),
    ]
