# Generated by Django 5.0.3 on 2024-04-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0014_publicacion_clics_tel_alter_grupoatributos_atributos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melicon',
            name='user_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
