# Generated by Django 5.0.3 on 2024-04-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0015_melicon_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='precio',
            field=models.CharField(max_length=50),
        ),
    ]
