# Generated by Django 5.0.3 on 2024-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0016_alter_publicacion_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('error', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='f_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
