# Generated by Django 5.0.3 on 2024-04-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0017_errores_alter_publicacion_f_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
    ]
