# Generated by Django 5.0.3 on 2024-04-12 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0018_publicacion_sincronizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoimagenes',
            name='video',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='f_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 12, 12, 35, 38, 172380, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
