# Generated by Django 5.0.3 on 2024-04-18 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0019_grupoimagenes_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='f_actualizacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
