# Generated by Django 5.0.3 on 2024-04-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0020_alter_publicacion_f_actualizacion'),
        ('multiple_upload', '0002_image_model_image_model_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.AlterField(
            model_name='grupoimagenes',
            name='imagenes',
            field=models.ManyToManyField(to='multiple_upload.image'),
        ),
    ]
