# Generated by Django 5.0.3 on 2024-04-18 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espasa_info', '0003_alter_crm_options_rename_modelo_crm_desc_and_more'),
        ('meli_api', '0021_delete_imagen_alter_grupoimagenes_imagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='stock',
        ),
        migrations.AddField(
            model_name='modelo',
            name='espasa_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='espasa_info.crm'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('gold_premium', 'Gold Premium')], max_length=30),
        ),
    ]
