# Generated by Django 5.0.3 on 2024-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0022_remove_modelo_codigo_remove_modelo_stock_and_more'),
        ('multiple_upload', '0003_alter_image_model_alter_image_model_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoimagenes',
            name='imagenes',
            field=models.ManyToManyField(blank=True, null=True, to='multiple_upload.image'),
        ),
        migrations.AlterField(
            model_name='grupoimagenes',
            name='video',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
