# Generated by Django 5.0.3 on 2024-04-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0023_alter_grupoimagenes_imagenes_and_more'),
        ('multiple_upload', '0004_image_asd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoimagenes',
            name='imagenes',
            field=models.ManyToManyField(blank=True, to='multiple_upload.image'),
        ),
    ]
