# Generated by Django 5.0.3 on 2024-04-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_api', '0024_alter_grupoimagenes_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoimagenes',
            name='codigo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
