version: '3'

services:
  meli-api-sidway:
    container_name: meli-api-sidway
    image: meli-api-sidway:v1
    volumes:
      - ../db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ../static:/app/static
      - ../usuarios/migrations:/app/usuarios/migrations
      - ../meli_api/migrations:/app/meli_api/migrations
      - ../lead/migrations:/app/lead/migrations
      - ../espasa_info/migrations:/app/espasa_info/migrations
      - ../multiple_upload/migrations:/app/multiple_upload/migrations
    ports:
      - "8010:8000"
    networks:
      - espasa-network

networks:
  espasa-network:
    driver: bridge
