version: '3'

services:
  meli-api-autos:
    container_name: meli-api-autos
    image: meli-api-autos:v1
    volumes:
      - ../db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./static:/app/static
      - ./usuarios/migrations:app/usuarios/migrations
      - ./meli_api/migrations:app/meli_api/migrations
      - ./lead/migrations:app/lead/migrations
      - ./espasa_info/migrations:app/espasa_info/migrations
      - ./multiple_upload/migrations:app/multiple_upload/migrations
    ports:
      - "8000:8000"
    networks:
      - orange-network

networks:
  orange-network:
    driver: bridge